### ISSUE TITLE
Fail to connect broker.

### ISSUE THREAD

**Issue by afsaredrisy** [danielkec/helidon-oci-streams-example#1]
Hi @danielkec, I tried your code and followed your [Medium: Helidon messaging with Oracle Streaming Service](https://medium.com/helidon/helidon-messaging-with-oracle-streaming-service-68e0ef423853) to setup OCI stream. I added required configurations in application.yaml, But I am getting warning. 
 
```

 [kafka-7] WARN  org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-example-group-id-1, groupId=example-group-id] Connection to node -1 ({my-stream-pool-bootstrap-server}/{someip}:9092) could not be established. Broker may not be available.
 [kafka-7] WARN  org.apache.kafka.clients.NetworkClient - [Consumer clientId=consumer-example-group-id-1, groupId=example-group-id] Bootstrap broker {my-stream-pool-bootstrap-server}:9092 (id: -1 rack: null) disconnected

```
I have compare {my-stream-pool-bootstrap-server} in OCI console it is same, While trying to publish `to-stream` using /send/{msg}, But message is not being published.  I am unclear where to look, Any idea?

**Comment by danielkec** [comment]
Caused by VPN issue
